//go:build !minimal

package cmd

import (
	"fmt"
	"io"

	"github.com/rokeller/spartan/server"
	"github.com/spf13/cobra"
	"k8s.io/klog/v2"
)

// previewHeadersCmd represents the preview-headers command
var previewHeadersCmd = &cobra.Command{
	Use:     "headers",
	Aliases: []string{"preview-headers"},
	Short:   "Preview generated response headers",
	Long:    `Prints response headers generated by spartan for the current configuration.`,
	RunE:    runPreviewHeaders,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("previewHeaders called")
	},
}

func init() {
	rootCmd.AddCommand(previewHeadersCmd)
}

func runPreviewHeaders(cmd *cobra.Command, args []string) error {
	klog.SetOutput(cmd.OutOrStderr())
	if config, err := getConfig(); nil != err {
		return err
	} else {
		printHeaders(cmd, config)
		return nil
	}
}

func printHeaders(cmd *cobra.Command, config *server.Config) {
	w := cmd.OutOrStdout()
	printCachePolicy(cmd, &config.Server.Cache.DefaultPolicy)
	fmt.Fprintln(w)
	printContentSecurityPolicy(cmd,
		config.Server.Security.GetContentSecurityPolicy(),
		config.Server.Security.GetContentTypeOptionsNoSniff())
	fmt.Fprintln(w)
	printPermissionsPolicy(cmd, config.Server.Security.GetPermissionsPolicy())
	fmt.Fprintln(w)
	printReferrerPolicy(cmd, config.Server.Security.GetReferrerPolicy())
	fmt.Fprintln(w)
	printReportingEndpoints(cmd, config.Server.Security.ReportingEndpoints)
	fmt.Fprintln(w)
	printStrictTransportSecurityPolicy(cmd, config.Server.Security.GetStrictTransportSecurityPolicy())
	fmt.Fprintln(w)
}

func printCachePolicy(cmd *cobra.Command, p *server.CachePolicy) {
	w := cmd.OutOrStdout()
	printTitle(w, "Caching headers")
	v := p.CacheControlHeaderValue()
	if v != "" {
		fmt.Fprintf(w, "Cache-Control: %s\n", v)
	} else {
		printWarning(w, "Cache-Control header not configured.")
	}
}

func printContentSecurityPolicy(cmd *cobra.Command, p *server.ContentSecurityPolicy, noSniff bool) {
	w := cmd.OutOrStdout()
	printTitle(w, "Content security headers")
	nm := server.NonceMap{}
	ctx := server.WithNonceMap(cmd.Context(), nm)
	v := p.HeaderValue(ctx)
	if len(nm) > 0 {
		printNote(w, "Note: nonce values change every time.")
	}

	if p.ReportOnly {
		fmt.Fprintf(w, "Content-Security-Policy-Report-Only: %s\n", v)
	} else {
		fmt.Fprintf(w, "Content-Security-Policy: %s\n", v)
	}

	if noSniff {
		fmt.Fprintln(w, "X-Content-Type-Options: nosniff")
	}
}

func printPermissionsPolicy(cmd *cobra.Command, p *server.PermissionsPolicy) {
	w := cmd.OutOrStdout()
	printTitle(w, "Permissions policy headers")
	fmt.Fprintf(w, "Permissions-Policy: %s\n", p.HeaderValue())
}

func printReferrerPolicy(cmd *cobra.Command, p *server.ReferrerPolicy) {
	w := cmd.OutOrStdout()
	printTitle(w, "Referrer policy headers")
	fmt.Fprintf(w, "Referrer-Policy: %s\n", p.Value.Value())
}

func printReportingEndpoints(cmd *cobra.Command, e *server.ReportingEndpoints) {
	w := cmd.OutOrStdout()
	printTitle(w, "Reporting endpoints headers")

	if nil != e && e.HasEndpoints() {
		fmt.Fprintf(w, "Reporting-Endpoints: %s\n", e.ReportingEndpointsHeaderValue())
	} else {
		printWarning(w, "Reporting endpoints not configured.")
	}
}

func printStrictTransportSecurityPolicy(cmd *cobra.Command, p *server.StrictTransportSecurityPolicy) {
	w := cmd.OutOrStdout()
	printTitle(w, "Transport security headers")
	fmt.Fprintf(w, "Strict-Transport-Security: %s\n", p.StsHeaderValue())
}

func printTitle(w io.Writer, title string) {
	fmt.Fprintf(w, "\033[1m\033[4m%s\033[0m\n", title)
}

func printWarning(w io.Writer, text string) {
	fmt.Fprintf(w, "\033[33m%s\033[0m\n", text)
}

func printNote(w io.Writer, text string) {
	fmt.Fprintf(w, "\033[34m\033[3m%s\033[0m\n", text)
}
