name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: |
            go.sum

      - name: Build spartan
        run: go build

      - name: Build container image
        run: |
          docker image build -t spartan .
