name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: |
            go.sum

      - name: Build spartan
        run: |
          echo 'Building minimal ...'
          go build -tags minimal

          echo 'Building all ...'
          go build

      - name: Test Server
        run: go test ./...

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build container image
        run: |
          echo 'Building minimal image ...'
          docker image build --build-arg SPARTAN_TAGS=minimal -t spartan .

          echo 'Building image with all ...'
          docker image build -t spartan:tools .
